name: Rust CI Tests

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Build and Test Terminal Vec2
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Project
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
